# Form implementation generated from reading ui file 'book-card.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(337, 475)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pictureLabel = QtWidgets.QLabel(parent=Form)
        self.pictureLabel.setMinimumSize(QtCore.QSize(170, 170))
        self.pictureLabel.setMaximumSize(QtCore.QSize(170, 170))
        self.pictureLabel.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.pictureLabel.setText("")
        self.pictureLabel.setObjectName("pictureLabel")
        self.verticalLayout.addWidget(self.pictureLabel, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.nameLabal = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nameLabal.setFont(font)
        self.nameLabal.setObjectName("nameLabal")
        self.verticalLayout.addWidget(self.nameLabal, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.nameText = QtWidgets.QLabel(parent=Form)
        self.nameText.setObjectName("nameText")
        self.verticalLayout.addWidget(self.nameText, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.authorLabel = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.authorLabel.setFont(font)
        self.authorLabel.setObjectName("authorLabel")
        self.verticalLayout.addWidget(self.authorLabel, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.authorText = QtWidgets.QLabel(parent=Form)
        self.authorText.setObjectName("authorText")
        self.verticalLayout.addWidget(self.authorText, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.yearLabel = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.yearLabel.setFont(font)
        self.yearLabel.setObjectName("yearLabel")
        self.verticalLayout.addWidget(self.yearLabel, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.yearText = QtWidgets.QLabel(parent=Form)
        self.yearText.setObjectName("yearText")
        self.verticalLayout.addWidget(self.yearText, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.genreLabel = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.genreLabel.setFont(font)
        self.genreLabel.setObjectName("genreLabel")
        self.verticalLayout.addWidget(self.genreLabel, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.genreText = QtWidgets.QLabel(parent=Form)
        self.genreText.setObjectName("genreText")
        self.verticalLayout.addWidget(self.genreText, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.nameLabal.setText(_translate("Form", "Название"))
        self.nameText.setText(_translate("Form", "TextLabel"))
        self.authorLabel.setText(_translate("Form", "Автор"))
        self.authorText.setText(_translate("Form", "TextLabel"))
        self.yearLabel.setText(_translate("Form", "Год выпуска"))
        self.yearText.setText(_translate("Form", "TextLabel"))
        self.genreLabel.setText(_translate("Form", "Жанр"))
        self.genreText.setText(_translate("Form", "TextLabel"))
