# Form implementation generated from reading ui file 'library.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 551)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.selectSort = QtWidgets.QComboBox(parent=self.centralwidget)
        self.selectSort.setObjectName("selectSort")
        self.selectSort.addItem("")
        self.selectSort.addItem("")
        self.verticalLayout_2.addWidget(self.selectSort, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.sortBy = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.sortBy.setObjectName("sortBy")
        self.verticalLayout_2.addWidget(self.sortBy, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.findButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.findButton.setMinimumSize(QtCore.QSize(0, 60))
        self.findButton.setMaximumSize(QtCore.QSize(16777215, 60))
        self.findButton.setObjectName("findButton")
        self.horizontalLayout.addWidget(self.findButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.result = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.result.setWidgetResizable(True)
        self.result.setObjectName("result")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 776, 407))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.result.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.result)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.selectSort.setItemText(0, _translate("MainWindow", "Автор"))
        self.selectSort.setItemText(1, _translate("MainWindow", "Название"))
        self.findButton.setText(_translate("MainWindow", "Искать"))
